---

language: 'english' # english, spanish, german, chinese

debug: false

discord: true

webhook_url: "https://discordapp.com/api/webhooks/469730298490519559/R8IkBFX_bgxydgma6nAMRnPvvnF2qRl6dT2zEuqLN9_c-Zk2Pxzv4fBWf7rooXT3lF3A"
webhook_name: "Funny Block"
webhook_playerChat?: true
webhook_playerJoin?: true
webhook_playerLeave?: true
webhook_playerDeath?: true

webhook_playerChatFormat: "[ {player} | {time} ] : {msg}"
webhook_playerJoinFormat: "{player} Joined the server !"
webhook_playerLeaveFormat: "{player} Left the server !"
webhook_playerDeathFormat: "{player} Died !"

other_pluginEnabled?: true
other_pluginDisabled?: true
other_pluginEnabledFormat: "Plugin Enabled !"
other_pluginDisabledFormat: "Plugin Disabled !"
...
