---
version: 4
identity: ""
secret: ""
lock: false
vote-expiration: 7
multi-server:
  enabled: false
  role: master
  mysql:
    host: localhost
    port: 3306
    username: pocketvote
    password: pocketvote
    database: pocketvote
onvote:
  run-cmd: []
  online-cmd: []
votes: []
...
