categories:
  construction:
    img-url: 'https://www.digminecraft.com/block_recipes/images/bricks.png'
    text: "Construction"
  equipment:
    img-path: 'textures/items/diamond_sword'
    text: "Equipment"
  items:
    img-url: 'https://www.digminecraft.com/basic_recipes/images/bed.png'
    text: "Items"
  nature:
    img-url: 'https://www.digminecraft.com/materials/images/grass_block.png'
    text: "Nature"

items:
  # itemId : itemMeta : optionName : price per item count : url/path : imgpath
  # Example : 276:0:Sword:2500:path:textures/items/diamond_sword
  construction:
    - "5:0:Oak Wood Planks:50:url:https://www.digminecraft.com/basic_recipes/images/oak_wood_plank.png"
    - "5:1:Spruce Wood Planks:50:url:https://www.digminecraft.com/basic_recipes/images/spruce_wood_plank.png"
    - "5:2:Birch Wood Planks:50:url:https://www.digminecraft.com/basic_recipes/images/birch_wood_plank.png"
    - "5:3:Jungle Wood Planks:50:url:https://www.digminecraft.com/basic_recipes/images/jungle_wood_plank.png"
    - "5:4:Acacia Wood Planks:50:url:https://www.digminecraft.com/basic_recipes/images/acacia_wood_plank.png"
    - "5:5:Dark Oak Wood Planks:50:url:https://www.digminecraft.com/basic_recipes/images/dark_oak_wood_plank.png"
    - "98:0:Stone Bricks:200:path:textures/blocks/stonebrick"
    - "20:0:Glass:900:url:https://www.digminecraft.com/block_recipes/images/glass.png"
    - "102:0:Glass Pane:150:path:textures/blocks/glass"
    - "24:0:Sandstone:100:path:textures/blocks/sandstone_normal"
    - "155:0:Block of Quartz:400:path:textures/blocks/quartz_block_side"
    - "44:0:Stone Slab:350:path:textures/blocks/stone_slab_side"
    - "45:0:Brick Block:400:path:textures/blocks/brick"
    - "53:0:Wooden Stairs:100:url:https://www.digminecraft.com/block_recipes/images/oak_wood_stairs.png"
    - "134:0:Spruce Stairs:100:url:https://www.digminecraft.com/block_recipes/images/spruce_wood_stairs.png"
    - "135:0:Birch Stairs:100:url:https://www.digminecraft.com/block_recipes/images/birch_wood_stairs.png"
    - "136:0:Jungle Stairs:100:url:https://www.digminecraft.com/block_recipes/images/jungle_wood_stairs.png"
    - "163:0:Acacia Stairs:100:url:https://www.digminecraft.com/block_recipes/images/acacia_wood_stairs.png"
    - "164:0:Dark Oak Stairs:100:url:https://www.digminecraft.com/block_recipes/images/dark_oak_wood_stairs.png"
    - "108:0:Brick Stairs:150:url:https://www.digminecraft.com/block_recipes/images/brick_stairs.png"
    - "109:0:Stone Brick Stairs:150:url:https://www.digminecraft.com/block_recipes/images/stone_brick_stairs.png"
    - "156:0:Quartz Stairs:200:url:https://www.digminecraft.com/block_recipes/images/quartz_stairs.png"
    - "180:0:Red Sandstone Stairs:200:url:https://www.digminecraft.com/block_recipes/images/red_sandstone_stairs.png"
    - "203:0:Purpur Stairs:200:url:https://www.digminecraft.com/block_recipes/images/purpur_stairs.png"
    - "324:0:Wooden Door:150:url:https://www.digminecraft.com/mechanism_recipes/images/oak_door.png"
    - "427:0:Spruce Door:150:url:https://www.digminecraft.com/mechanism_recipes/images/spruce_door.png"
    - "428:0:Birch Door:150:url:https://www.digminecraft.com/mechanism_recipes/images/birch_door.png"
    - "429:0:Jungle Door:150:url:https://www.digminecraft.com/mechanism_recipes/images/jungle_door.png"
    - "430:0:Acacia Door:150:url:https://www.digminecraft.com/mechanism_recipes/images/acacia_door.png"
    - "431:0:Dark Oak Door:150:url:https://www.digminecraft.com/mechanism_recipes/images/dark_oak_door.png"
    - "330:0:Iron Door:300:url:https://www.digminecraft.com/mechanism_recipes/images/iron_door.png"
    - "96:0:Trap Door:200:url:https://www.digminecraft.com/mechanism_recipes/images/trapdoor.png"
    - "101:0:Iron Bars:300:path:textures/blocks/iron_bars"
    - "173:0:Block Of Coal:3150:url:https://www.digminecraft.com/block_recipes/images/coal_block.png"
    - "41:0:Block Of Gold:4500:url:https://www.digminecraft.com/block_recipes/images/gold_block.png"
    - "42:0:Block Of Iron:9000:url:https://www.digminecraft.com/block_recipes/images/iron_block.png"
    - "57:0:Block Of Diamond:18000:url:https://www.digminecraft.com/block_recipes/images/diamond_block.png"
    - "133:0:Block Of Emerald:4950:url:https://www.digminecraft.com/block_recipes/images/emerald_block.png"
    - "22:0:Lapis Lazuli Block:5400:url:https://www.digminecraft.com/block_recipes/images/lapis_lazuli_block.png"    
  equipment:
    - "268:0:Wooden Sword:500:path:textures/items/wood_sword"
    - "272:0:Stone Sword:1000:path:textures/items/stone_sword"
    - "267:0:Golden Sword:2000:path:textures/items/gold_sword"
    - "283:0:Iron Sword:4000:path:textures/items/iron_sword"
    - "276:0:Diamond Sword:8000:path:textures/items/diamond_sword"
    - "261:0:Bow:800:path:textures/items/bow_standby"
    - "262:0:Arrow:400:path:textures/items/arrow"
    - "270:0:Wooden Pickaxe:100:path:textures/items/wood_pickaxe"
    - "274:0:Stone Pickaxe:200:path:textures/items/stone_pickaxe"
    - "257:0:Iron Pickaxe:400:path:textures/items/iron_pickaxe"
    - "285:0:Golden Pickaxe:800:path:textures/items/gold_pickaxe"
    - "278:0:Diamond Pickaxe:1600:path:textures/items/diamond_pickaxe"
    - "298:0:Leather Cap:250:path:textures/items/leather_helmet"
    - "299:0:Leather Tunic:250:path:textures/items/leather_chestplate"
    - "300:0:Leather Pants:250:path:textures/items/leather_leggings"
    - "301:0:Leather Boots:250:path:textures/items/leather_boots"
    - "314:0:Golden Helmet:500:path:textures/items/gold_helmet"
    - "315:0:Golden Chestplate:500:path:textures/items/gold_chestplate"
    - "316:0:Golden Leggings:500:path:textures/items/gold_leggings"
    - "317:0:Golden Boots:500:path:textures/items/gold_boots"
    - "306:0:Iron Helmet:1000:path:textures/items/iron_helmet"
    - "307:0:Iron Chestplate:1000:path:textures/items/iron_chestplate"
    - "308:0:Iron Leggings:1000:path:textures/items/iron_leggings"
    - "309:0:Iron Boots:1000:path:textures/items/iron_boots"
    - "302:0:Chain Helmet:2000:path:textures/items/chainmail_helmet"
    - "303:0:Chain Chestplate:2000:path:textures/items/chainmail_chestplate"
    - "304:0:Chain Leggings:2000:path:textures/items/chainmail_leggings"
    - "305:0:Chain Boots:2000:path:textures/items/chainmail_boots"
    - "310:0:Diamond Helmet:4000:path:textures/items/diamond_helmet"
    - "311:0:Diamond Chestplate:4000:path:textures/items/diamond_chestplate"
    - "312:0:Diamond Leggings:4000:path:textures/items/diamond_leggings"
    - "313:0:Diamond Boots:4000:path:textures/items/diamond_boots"
    - "297:0:Bread:30:path:textures/items/bread"
    - "347:0:Clock:850:path:textures/items/clock_00"
    - "345:0:Compass:900:path:textures/items/compass_16"
    - "443:0:Elytra:800:path:textures/items/elytra"
  items:
    - "58:0:Crafting Table:60:url:https://www.digminecraft.com/basic_recipes/images/crafting_table.png"
    - "50:0:Torch:45:path:textures/blocks/torch_on"
    - "47:0:Bookshelf:500:path:textures/blocks/bookshelf"
    - "54:0:Chest:100:url:https://www.digminecraft.com/basic_recipes/images/chest.png"
    - "326:0:Water Bucket:250:path:textures/items/bucket_water"
    - "327:0:Lava Bucket:250:path:textures/items/bucket_lava"
    - "263:0:Coal:350:path:textures/items/coal"
    - "266:0:Gold Ingot:500:path:textures/items/gold_ingot"
    - "265:0:Iron Ingot:1000:path:textures/items/iron_ingot"
    - "264:0:Diamond:2000:path:textures/items/diamond"
    - "397:0:Dragon Head:850:url:https//img4.hostingpics.net/pics/436796skulldragon.png"
    - "397:0:Wither Skeleton Skull:850:url:https//img4.hostingpics.net/pics/826437skullwither.png"
    - "397:0:Creeper Head:850:url:https//img4.hostingpics.net/pics/556676skullcreeper.png"
    - "397:0:Zombie Head:850:url:https//img4.hostingpics.net/pics/415562skullzombie.png"
    - "307:0:Skeleton Head:850:url:https//img4.hostingpics.net/pics/589367skullskeleton.png"
    - "466:0:Enchanted Apple:1000:url:https//www.digminecraft.com/food_recipes/images/golden_apple2.png"
    - "322:0:Golden Apple:500:url:https//www.digminecraft.com/food_recipes/images/golden_apple.png"
    - "396:0:Golden Carrot:500:url:https//www.digminecraft.com/food_recipes/images/golden_carrot.png"
  nature:
    - "2:0:Grass:10:url:https://www.digminecraft.com/materials/images/grass_block.png"
    - "1:0:Stone:50:path:textures/blocks/stone"
    - "17:0:Oak Wood:50:path:textures/blocks/log_oak"
    - "88:0:Snow:50:path:textures/blocks/snow"