#Tệp cấu hình của RestartMe v1.3.0
broadcastInterval: 1800
#Sets the interval of the countdown before broadcast, in seconds
broadcastMessage: "§eServer sẽ khởi động lại trong {RESTART_FORMAT_TIME}."
#Sets the message format, will broadcast at the intervals set in broadcastInterval, refer to values.txt for entire list of usable values
countdownMessage: "§eServer khởi động lại trong §6{RESTART_TIME} giây..."
#Sets the message format, will broadcast during countdown, refer to values.txt for entire list of usable values
displayType: chat
#Sets how players get the countdown message, three options: chat, popup, tip
memoryLimit: 500M
#Sets the max memory that can be allocated before server restarts due to overload
#B = byte; K = kilobyte; M = megabyte; G = gigabyte; T = terabyte
overloadQuitMessage: "§eServer đã khởi dộng lại vì bộ nhớ quá tải."
#Sets the message sent to a player when they are kicked because of a server restart triggered by a memory overload
quitMessage: "§eServer đang khởi động lại...\n§eBạn có thể vào lại sau khoảng 5 giây"
#Sets the message sent to a player when they are kicked because of a server restart
restartInterval: 60
#Sets the interval of the server restart, in minutes
restartOnOverload: true
#Set to true to allow server restarts when the server's memory is overloaded
startCountdown: 10
#Sets the time when to initiate a countdown, n seconds from restarting