---
version: 1.4.10-6
default-factions-plugin: FactionsPro
groups:
  YouTuber:
    nametag: '§l§6[§a{fac_name}§6]&b&l✿§e»﹏§cƴᴏᴜ§7ƭᴜɓε§e﹏«§b✿ &6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&b&l✿§e»﹏§cƴᴏᴜ§7ƭᴜɓε§e﹏«§b✿ &6&r{display_name} &b☞ {msg}'
  Owner:
    nametag: '§l§6[§a{fac_name}§6]&d&l♚§3﹏§bOwner§3﹏§d♚&b&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&d&l♚§3﹏§bOwner§3﹏§d♚&b&r{display_name} &b☞ {msg}'
  Guest:
    nametag: '§l§6[§a{fac_name}§6]&b&l❁§a◕§9﹏§eℳεᵯɓεɾ§9﹏§a◕§b❁&f&r {display_name}'
    chat: '§l§6[§a{fac_name}§6]&b&l❁§a◕§9﹏§eℳεᵯɓεɾ§9﹏§a◕§b❁&f&r {display_name} &7☞ {msg}'
  Admin:
    nametag: '§l§6[§a{fac_name}§6]&d&l♚§3﹏§bAdmin§3﹏§d♚&3&r{display_name}'
    chat: ' §l§6[§a{fac_name}§6]&d&l♚§3﹏§bAdmin§3﹏§d♚&3&r{display_name} &b☞ {msg}'
  Police:
    nametag: '§l§6[§a{fac_name}§6]&e&l❂§b◬‿§aPolice§b‿◬§e❂&f&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&e&l❂§b◬‿§aPolice§b‿◬§e❂&f&r{display_name} &b☞ {msg}'
  Co-Owner:
    nametag: '§l§6[§a{fac_name}§6]&e&lミ★§a⊶§bℭo§d❍ཡɳεɾ§a⊷§e★彡&6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&e&lミ★§a⊶§bℭo§d❍ཡɳεɾ§a⊷§e★彡&6&r{display_name} &6☞ {msg}'
  OP:
    nametag: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§b❍§dƤ§6﹏۩§c☠&6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§b❍§dƤ§6﹏۩§c☠&6&r{display_name} &6☞ {msg}'
  Co-OP:
    nametag: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo&7-§dOP§6﹏۩§c☠&6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo&7-§dOP§6﹏۩§c☠&6&r{display_name} &6☞ {msg}'
  Coder:
    nametag: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo§dder§6﹏۩§c☠&6&r{display_name}'
    chat: '§l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo§dder§6﹏۩§c☠&6&r{display_name} &6☞ {msg}'
...
