---
version: 1.4.10-6
default-factions-plugin: FactionsPro
groups:
  YouTuber:
    nametag: §l§6[§a{fac_name}§6]&b&l✿§e»﹏§cƴᴏᴜ§7ƭᴜɓε§e﹏«§b✿ &6&r{display_name}
    chat: §l§6[§a{fac_name}§6]&b&l✿§e»﹏§cƴᴏᴜ§7ƭᴜɓε§e﹏«§b✿ &6&r{display_name} &b☞ {msg}
  Owner:
    nametag: §l§6[§a{fac_name}§6]&d&l♚§3﹏§bOwner§3﹏§d♚&b&r{display_name}
    chat: §l§6[§a{fac_name}§6]&d&l♚§3﹏§bOwner§3﹏§d♚&b&r{display_name} &b☞ {msg}
  Member:
    nametag: §l§6[§a{fac_name}§6]&b&l❁§a◕§9﹏§eℳεᵯɓεɾ§9﹏§a◕§b❁&f&r {display_name}
    chat: §l§6[§a{fac_name}§6]&b&l❁§a◕§9﹏§eℳεᵯɓεɾ§9﹏§a◕§b❁&f&r {display_name} &7☞
      {msg}
  Admin:
    nametag: §l§6[§a{fac_name}§6]&d&l♚§3﹏§bAdmin§3﹏§d♚&3&r{display_name}
    chat: §l§6[§a{fac_name}§6]&d&l♚§3﹏§bAdmin§3﹏§d♚&3&r{display_name} &b☞ {msg}
  Police:
    nametag: §l§6[§a{fac_name}§6]&e&l❂§b◬‿§aPolice§b‿◬§e❂&f&r{display_name}
    chat: §b•{fac_name}• §l§a[ΔPoliceΔ] §r{display_name} §e>{msg}<
  Co-Owner:
    nametag: §l§6[§a{fac_name}§6]&e&lミ★§a⊶§bℭo§d❍ཡɳεɾ§a⊷§e★彡&6&r{display_name}
    chat: §l§6[§a{fac_name}§6]&e&lミ★§a⊶§bℭo§d❍ཡɳεɾ§a⊷§e★彡&6&r{display_name} &6☞ {msg}
  OP:
    nametag: §l§6[§a{fac_name}§6]&l§a☘§6۩﹏§b❍§dƤ§6﹏۩§c☠&6&r{display_name}
    chat: §l§6[§a{fac_name}§6]&l§a☘§6۩﹏§b❍§dƤ§6﹏۩§c☠&6&r{display_name} &6☞ {msg}
  Co-OP:
    nametag: §l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo&7-§dOP§6﹏۩§c☠&6&r{display_name}
    chat: §l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo&7-§dOP§6﹏۩§c☠&6&r{display_name} &6☞ {msg}
  Coder:
    nametag: §l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo§dder§6﹏۩§c☠&6&r{display_name}
    chat: §l§6[§a{fac_name}§6]&l§a☘§6۩﹏§bCo§dder§6﹏۩§c☠&6&r{display_name} &6☞ {msg}
  Topmoney:
    nametag: §l§6[§a{fac_name}§6]&e&lミ★§a⊶§bRich§dKid§a⊷§e★彡&6&r{display_name}
    chat: §l§6[§a{fac_name}§6]&e&lミ★§a⊶§bRich§dKid§a⊷§e★彡&6&r{display_name} &6☞ {msg}
  MVP:
    nametag: '&8&l[MVP]&f&r {display_name}'
    chat: '&8&l[MVP]&f&r {display_name} &7> {msg}'
  Builder:
    nametag: '[][§e•§b...§aBuilder§b...§e•§r][] {display_name}'
    chat: §0[§7{fac_name}§0] §1•›…§d§lBuilder§r§1…‹• §e§l{display_name}§r §7➡ §b{msg}
  God:
    nametag: §l§6[§a{fac_name}§6]&b&l❁§a◕§7﹏§6God§7﹏§a◕§b❁&f&r {display_name}
    chat: §l§6[§a{fac_name}§6]&b&l❁§a◕§7﹏§6God§7﹏§a◕§b❁&f&r {display_name} &7☞ {msg}
  Nói_nhiều:
    chat: kẹc_kẹc_kẹc_kẹc_Tooo §e§l{display_name} §a kẹc kẹc kẹc kẹc kẹc
    nametag: '&8&l[Nói_nhiều]&f&r {display_name}'
  Master:
    chat: §6[] §c[§eMaster§c] §5{display_name} [Trùm_Server] → §e{msg}
    nametag: '&8&l[Master]&f&r {display_name}'
  POLICE:
    nametag: '&8&l[POLICE]&f&r {display_name}'
    chat: '&8&l[POLICE]&f&r {display_name} &7> {msg}'
  AFK:
    chat: '[] §c§l[§eAFK§c] §f§r§f{display_name} §e§l§o→ {msg} [AFKTeam]'
    nametag: '&8&l[AFK]&f&r {display_name}'
  Buidd:
    nametag: '&8&l[Buidd]&f&r {display_name}'
    chat: '&8&l[Buidd]&f&r {display_name} &7> {msg}'
  Pan:
    nametag: '&8&l[Pan]&f&r {display_name}'
    chat: '&8&l[Pan]&f&r {display_name} &7> {msg}'
...
