#Positions of the floating texts
Positions:
    - world: hub
      x: -67
      "y": 20
      z: 11
#API-Key of your server provided by minecraftpocket-servers.com
API-Key: "gnGiCLwGzixnFU9sMw5p4SJey4pcCSNxtZF"
#Amount of voters who shall be shown (Max: 500)
Amount: 10
#Update interval of the query to the server in seconds
Update-Interval: 180
#Header of the floating text particle
Header: "§6Top vote trong tháng này"
#Text for every row after the header
Text: "§a{player}: §d{votes} vote"
